require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChrysalisController do

  # This should return the minimal set of attributes required to create a valid
  # Chrysali. As you add validations to Chrysali, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "title" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChrysalisController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all chrysalis as @chrysalis" do
      chrysali = Chrysali.create! valid_attributes
      get :index, {}, valid_session
      assigns(:chrysalis).should eq([chrysali])
    end
  end

  describe "GET show" do
    it "assigns the requested chrysali as @chrysali" do
      chrysali = Chrysali.create! valid_attributes
      get :show, {:id => chrysali.to_param}, valid_session
      assigns(:chrysali).should eq(chrysali)
    end
  end

  describe "GET new" do
    it "assigns a new chrysali as @chrysali" do
      get :new, {}, valid_session
      assigns(:chrysali).should be_a_new(Chrysali)
    end
  end

  describe "GET edit" do
    it "assigns the requested chrysali as @chrysali" do
      chrysali = Chrysali.create! valid_attributes
      get :edit, {:id => chrysali.to_param}, valid_session
      assigns(:chrysali).should eq(chrysali)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Chrysali" do
        expect {
          post :create, {:chrysali => valid_attributes}, valid_session
        }.to change(Chrysali, :count).by(1)
      end

      it "assigns a newly created chrysali as @chrysali" do
        post :create, {:chrysali => valid_attributes}, valid_session
        assigns(:chrysali).should be_a(Chrysali)
        assigns(:chrysali).should be_persisted
      end

      it "redirects to the created chrysali" do
        post :create, {:chrysali => valid_attributes}, valid_session
        response.should redirect_to(Chrysali.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved chrysali as @chrysali" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chrysali.any_instance.stub(:save).and_return(false)
        post :create, {:chrysali => { "title" => "invalid value" }}, valid_session
        assigns(:chrysali).should be_a_new(Chrysali)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chrysali.any_instance.stub(:save).and_return(false)
        post :create, {:chrysali => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested chrysali" do
        chrysali = Chrysali.create! valid_attributes
        # Assuming there are no other chrysalis in the database, this
        # specifies that the Chrysali created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Chrysali.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => chrysali.to_param, :chrysali => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested chrysali as @chrysali" do
        chrysali = Chrysali.create! valid_attributes
        put :update, {:id => chrysali.to_param, :chrysali => valid_attributes}, valid_session
        assigns(:chrysali).should eq(chrysali)
      end

      it "redirects to the chrysali" do
        chrysali = Chrysali.create! valid_attributes
        put :update, {:id => chrysali.to_param, :chrysali => valid_attributes}, valid_session
        response.should redirect_to(chrysali)
      end
    end

    describe "with invalid params" do
      it "assigns the chrysali as @chrysali" do
        chrysali = Chrysali.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chrysali.any_instance.stub(:save).and_return(false)
        put :update, {:id => chrysali.to_param, :chrysali => { "title" => "invalid value" }}, valid_session
        assigns(:chrysali).should eq(chrysali)
      end

      it "re-renders the 'edit' template" do
        chrysali = Chrysali.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chrysali.any_instance.stub(:save).and_return(false)
        put :update, {:id => chrysali.to_param, :chrysali => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested chrysali" do
      chrysali = Chrysali.create! valid_attributes
      expect {
        delete :destroy, {:id => chrysali.to_param}, valid_session
      }.to change(Chrysali, :count).by(-1)
    end

    it "redirects to the chrysalis list" do
      chrysali = Chrysali.create! valid_attributes
      delete :destroy, {:id => chrysali.to_param}, valid_session
      response.should redirect_to(chrysalis_url)
    end
  end

end
